### ISSUE TITLE
No sound in version 2.1.11

### ISSUE THREAD

**Issue by Recydywa** [mmartinortiz/retro-virtual-machine-snap#5]
I installed this snap today, but unfortunately it doesn't have sound.

When running from terminal:

```
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_id returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM dmix
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_id returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM dmix:0
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_id returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM dmix:0,0
ALSA lib confmisc.c:165:(snd_config_get_card) Cannot get card index for 0
ALSA lib confmisc.c:165:(snd_config_get_card) Cannot get card index for 0
ALSA lib confmisc.c:165:(snd_config_get_card) Cannot get card index for 0
/dev/shm/jack_db-1000/__db.001: No such file or directory
Cannot open DB environment: No such file or directory
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
```

**Comment by Recydywa** [comment]
And this after manually connecting the alsa interface

```
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
/dev/shm/jack_db-1000/__db.001: No such file or directory
Cannot open DB environment: No such file or directory
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
```
still no sound.

**Comment by mmartinortiz** [comment]
This is unfortunate, and it is not the first time that happens. I had it with version `2.1.3`, `2.1.6` and `2.1.10`. With `2.1.10`, without changing anything in the Snap, the sound started to work one day.

In my system `2.1.11` has sound. Can you try with the previous version, `2.1.10`?

**Comment by Recydywa** [comment]
There isn't 2.1.10 version to install.

I just looked at different snaps and I wonder if adding pulseaudio to plugs would resolve the issue.

Also I'm not entirely sure how RVM deals with games, but wouldn't the removable-media interface be a must if a user has roms in other partitions.

**Comment by mmartinortiz** [comment]
> There isn't 2.1.10 version to install.

True, I'm almost convinced that at some point it was possible...

These are the plugs that I have enabled:

![image](https://github.com/mmartinortiz/retro-virtual-machine-snap/assets/4763770/ef411601-cdfb-44ff-b8bc-e400d71c2bc8)

Maybe you want to try the official package [from its website](https://www.retrovirtualmachine.org/download/) and make sure that it has sound?

> Also I'm not entirely sure how RVM deals with games, but wouldn't the removable-media interface be a must if a user has roms in other partitions

When you open the menu for loading a tape/disk into an emulate machine, the RVM emulator opens the system's file dialog. From there you can access mounted drives.

**Comment by Recydywa** [comment]
No I meant that you should try adding pulseaudio to plugs in your snapcraft.yaml.

When I check that pulseaudio interface on my machine:

```
snap interface pulseaudio 
name:    pulseaudio
summary: allows operating as or interacting with the pulseaudio service
plugs:
  - backslash-maps
  - electron-store
  - electronplayer
  - heroic
  - minetest
  - open-syobon-action
  - opera
  - solarus
  - strimio-desktop
  - the-force-engine
  - warzone2100
slots:
  - snapd
```
and the audio-playback interface:

```
snap interface audio-playback 
name:    audio-playback
summary: allows audio playback via supporting services
plugs:
  - 0ad
  - audacious
  - cavalier
  - chromium
  - dolphin-emulator
  - dosbox-staging
  - electron-store
  - electronplayer
  - firefox
  - foliate
  - g4music
  - headset
  - heroic
  - kolourpaint
  - minetest
  - mmartinortiz-retro-virtual-machine
  - mousai
  - mrrescue
  - musicpod
  - nxengine-evo
  - ohmygiraffe
  - olivia
  - opennox
  - openra
  - opera
  - psst-gui
  - qsnapstore
  - spotify
  - spotify-qt
  - strimio-desktop
  - the-force-engine
  - thunderbird
  - warzone2100
slots:
  - snapd
```
So there are several snaps that use the pulseaudio interface on top of audio-playback. I didn't check all of those snaps but most of them have working sound.

**Comment by mmartinortiz** [comment]
However, the Snap with the version `2.1.11` has sound on my computer. If it would only be that slot, I should not have any sound. But it could also be that something has changed in `snap` and how slots are managed.

Which Snap version are you running? Mine is:
```bash
snap    2.61.3+22.04
snapd   2.61.3+22.04
series  16
ubuntu  22.04
```

Can you try some of the things discussed in [this previous issue](https://github.com/mmartinortiz/retro-virtual-machine-snap/issues/2)

**Comment by Recydywa** [comment]
I'm using `snapd` from the `edge` channel.

```
snap    2.62+git2043.g0324a4f
snapd   2.62+git2043.g0324a4f
series  16
ubuntu  24.04
kernel  6.8.0-11-generic
```
I've tried disconnecting and connecting both of the audio interfaces and that didn't work.

Also I have the official `.deb` package installed and in that version of RVM I have sound.

**Comment by Recydywa** [comment]
I tested this snap in two live versions of Ubuntu and in both cases no sound.

I used Ubuntu Unity 24.04 (2.60.4+23.10) the latest available `.iso` and KDE Neon (2.61.3+22.04) which is based on 22.04 LTS.

As you can see both have different version of snapd and both are older.

**Comment by Recydywa** [comment]
I also tested live image of Ubuntu 22.04 LTS same thing no sound, and that's even after connecting alsa interface.

```
snap    2.61.2
snapd   2.61.2
series  16
ubuntu  22.04
kernel  5.15.0-25-generic
```
I really think you should try  adding pulseaudio to plugs in snapcraft.yaml.

```
apps:
  retro-virtual-machine:
    extensions: [gnome]
    command: usr/bin/RetroVirtualMachine
    desktop: usr/share/applications/rvm.desktop
    plugs:
      - alsa
      - unity7
      - home
      - audio-playback
      - joystick
      - bluez
```

**Comment by mmartinortiz** [comment]
> I really think you should try adding pulseaudio to plugs in snapcraft.yaml.

I had a quick look to the [Pulse Audio documentation](https://snapcraft.io/docs/pulseaudio-interface) and it is deprecated. The [audio-playback](https://snapcraft.io/docs/audio-playback-interface) interface is already enabled and connected (at least on my computer)

```bash
❯ snap connections mmartinortiz-retro-virtual-machine
Interfaz                Enchufe                                            Ranura                          Notas
alsa                    mmartinortiz-retro-virtual-machine:alsa            :alsa                           manual
audio-playback          mmartinortiz-retro-virtual-machine:audio-playback  :audio-playback                 -
bluez                   mmartinortiz-retro-virtual-machine:bluez           :bluez                          manual
content[gnome-42-2204]  mmartinortiz-retro-virtual-machine:gnome-42-2204   gnome-42-2204:gnome-42-2204     -
content[gtk-3-themes]   mmartinortiz-retro-virtual-machine:gtk-3-themes    gtk-common-themes:gtk-3-themes  -
content[icon-themes]    mmartinortiz-retro-virtual-machine:icon-themes     gtk-common-themes:icon-themes   -
content[sound-themes]   mmartinortiz-retro-virtual-machine:sound-themes    gtk-common-themes:sound-themes  -
desktop                 mmartinortiz-retro-virtual-machine:desktop         :desktop                        -
desktop-legacy          mmartinortiz-retro-virtual-machine:desktop-legacy  :desktop-legacy                 -
gsettings               mmartinortiz-retro-virtual-machine:gsettings       :gsettings                      -
home                    mmartinortiz-retro-virtual-machine:home            :home                           -
joystick                mmartinortiz-retro-virtual-machine:joystick        :joystick                       manual
opengl                  mmartinortiz-retro-virtual-machine:opengl          :opengl                         -
unity7                  mmartinortiz-retro-virtual-machine:unity7          :unity7                         -
wayland                 mmartinortiz-retro-virtual-machine:wayland         :wayland                        -
x11                     mmartinortiz-retro-virtual-machine:x11             :x11                            -
```
Later today (or along the weekend) I'll ask for help on the [Snapcraft forum](https://forum.snapcraft.io/)

**Comment by Recydywa** [comment]
Yet new snaps use that plug. I recently installed The Force Engine snap which is a new snap by the way and it has pulseaudio plug.

```
snap connections the-force-engine 
Interface               Plug                               Slot                            Notes
audio-playback          the-force-engine:audio-playback    :audio-playback                 -
content[gnome-42-2204]  the-force-engine:gnome-42-2204     gnome-42-2204:gnome-42-2204     -
content[gtk-3-themes]   the-force-engine:gtk-3-themes      gtk-common-themes:gtk-3-themes  -
content[icon-themes]    the-force-engine:icon-themes       gtk-common-themes:icon-themes   -
content[sound-themes]   the-force-engine:sound-themes      gtk-common-themes:sound-themes  -
desktop                 the-force-engine:desktop           :desktop                        -
desktop-legacy          the-force-engine:desktop-legacy    :desktop-legacy                 -
gsettings               the-force-engine:gsettings         :gsettings                      -
hardware-observe        the-force-engine:hardware-observe  -                               -
home                    the-force-engine:home              :home                           -
opengl                  the-force-engine:opengl            :opengl                         -
pulseaudio              the-force-engine:pulseaudio        -                               -
raw-input               the-force-engine:raw-input         -                               -
wayland                 the-force-engine:wayland           :wayland                        -
x11                     the-force-engine:x11               :x11
```
https://forum.snapcraft.io/t/the-force-engine-to-play-classics-like-star-wars-dark-forces-in-modern/33799

And this is in the snapcraft.yaml

```
apps:
  the-force-engine:
    command: usr/bin/theforceengine
    desktop: usr/share/applications/TheForceEngine.desktop
    common-id: io.github.theforceengine.tfe
    plugs:
      - desktop
      - opengl
      - audio-playback
      - hardware-observe
      - raw-input
      - pulseaudio
    environment:
      TFE_DATA_HOME: $SNAP_USER_COMMON/Data
    extensions:
      - gnome
```
https://gitlab.com/zygoon/the-force-engine-snap/-/blob/main/snapcraft.yaml?ref_type=heads

Also the snap has been created by:

https://www.linkedin.com/in/zygmuntkrynicki

https://listed.zygoon.pl

**Comment by mmartinortiz** [comment]
I've included the `pulseaudio` plug in the "latest/edge" version, can you try it?

**Comment by Recydywa** [comment]
Actually I've been trying to get the sound working on my own.

I've built the snap package with pulseaudio plug and that didn't get the sound working. Neither does your snap from edge channel.

I'm still trying other things, but now I can't even build the package.

**Comment by mmartinortiz** [comment]
Did you make any progress? We could ask for help in the Snap forum with our issue and the steps we took so far.

**Comment by Recydywa** [comment]
Yes I finally got it working.

I was trying to update the [Cannonball snap](https://github.com/Wimpressive-Snaps/cannonball-snap/issues/3) and in its snapcraft definition I found the solution.

[snapcraft-alsa](https://github.com/diddlesnaps/snapcraft-alsa?tab=readme-ov-file): ALSA for your snap package routing sound through Pulseaudio!

I added it and that was the main puzzle piece. I also had to change some other things and I added more plugs like the removable-media I mentioned. 

In stage packages there is now `libgl1-mesa-dri` without it I couldn't start the RVM snap, because it would complain about not finding graphics drivers. Also the xkb-data was needed under Wayland session of Gnome. Without that again the RVM snap wouldn't start and complain about missing `/usr/share/X11/xkb`.

```
name: mmartinortiz-retro-virtual-machine
title: 'Retro Virtual Machine'
version: '2.1.11'
summary: Emulator of the Amstrad CPC and the ZX Spectrum home computers # 79 char long summary
description: |
  Retro Virtual Machine is an Amstrad and Spectrum emulator that not only offers
  the capacity of emulating old machines, but also reproduces the old CRT look
  and feel as well as the sounds of our beloved old machines.

  This software is maintained and developed by Juan Carlos González Amestoy <rvm@retrovirtualmachine.org>.
  You can find more details in its home page: https://www.retrovirtualmachine.org/en/

  If you have issues with the Snap, feel free to open an issue in [its repository](https://github.com/mmartinortiz/retro-virtual-machine-snap)

grade: stable
confinement: strict
icon: snap/gui/logo.png
base: core22

architectures:
  - build-on: amd64

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa

parts:
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
   
  retro-virtual-machine:
    after: [ alsa-mixin ]
    source: https://static.retrovm.org/release/$SNAPCRAFT_PROJECT_VERSION/RetroVirtualMachine.$SNAPCRAFT_PROJECT_VERSION.Linux.x64.deb
    plugin: dump
    source-type: deb
    organize:
      retro-virtual-machinelib: retro-virtual-machine
      retro-virtual-machine: usr/bin/RetroVirtualMachine
    build-packages:
      - libasound2-dev
    stage-packages:
      - libgl1-mesa-dri
      - xkb-data
           
apps:
  retro-virtual-machine:
    command: usr/bin/RetroVirtualMachine
    command-chain:
      - snap/command-chain/alsa-launch
    desktop: usr/share/applications/rvm.desktop
    environment:
      ALWAYS_USE_PULSEAUDIO: 1
    plugs:
      - audio-playback
      - bluez
      - desktop
      - home
      - joystick
      - removable-media
      - unity7
      - opengl
      - wayland
      - x11
    extensions:
      - gnome
```
This is the snapcraft.yaml that worked with the snap installed in devmode. I hope that regular install will also work.

I tested it under my install of Ubuntu 24.04 development version with Unity 7, Gnome Wayland and instantWM. I also checked under live images of KDE Neon and Ubuntu Budgie 24.04 daily-live.
